# Generated by Django 4.1.5 on 2023-02-08 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamelist', '0001_initial'),
        ('profile_user', '0002_remove_profile_games'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='games',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gamelist.orderdetail'),
        ),
    ]
