# Generated by Django 4.1.5 on 2023-02-08 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamelist', '0001_initial'),
        ('profile_user', '0003_profile_games'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='games',
        ),
        migrations.AddField(
            model_name='profile',
            name='games',
            field=models.ManyToManyField(null=True, to='gamelist.game'),
        ),
    ]
