# Generated by Django 4.1.5 on 2023-02-08 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamelist', '0001_initial'),
        ('profile_user', '0005_alter_profile_games'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='games',
            field=models.ManyToManyField(null=True, to='gamelist.game'),
        ),
    ]
