# Generated by Django 4.1.5 on 2023-02-15 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamelist', '0003_rename_game_image_game_uploaded_game_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='game_image_steam_api',
        ),
        migrations.AlterField(
            model_name='game',
            name='uploaded_game_images',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
