# Generated by Django 4.1.5 on 2023-02-07 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamelist', '0003_alter_order_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='addess',
            new_name='address',
        ),
    ]
