# Generated by Django 4.1.5 on 2023-02-15 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamelist', '0004_remove_game_game_image_steam_api_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='uploaded_game_images',
            new_name='steam_image_api',
        ),
    ]
