# Generated by Django 4.1.5 on 2023-02-15 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamelist', '0005_rename_uploaded_game_images_game_steam_image_api'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='uploaded_game_image',
            field=models.ImageField(blank=True, default='/placeholder.png', null=True, upload_to=''),
        ),
    ]
