# Generated by Django 4.1.5 on 2023-02-18 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamelist', '0008_remove_review_customer_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='picture',
        ),
    ]
